Revert "chore(deps): bump cookie and express in /gemini/sample-apps/genwealth/api" (#1317)
Reverts GoogleCloudPlatform/generative-ai#1242

This is a breaking change that broke the deployment process. Example
error:

```
 > [api-build 5/5] RUN npx tsc --outDir /dist:
18.11 index.ts(111,59): error TS2769: No overload matches this call.
18.11   The last overload gave the following error.
18.11     Argument of type '(req: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, res: Response<any, Record<string, any>, number>) => Promise<...>' is not assignable to parameter of type 'RequestHandlerParams<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
18.11       Type '(req: Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>, res: Response<any, Record<string, any>, number>) => Promise<...>' is not assignable to type 'RequestHandler<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
18.11         Type 'Promise<Response<any, Record<string, any>, number> | undefined>' is not assignable to type 'void | Promise<void>'.
18.11           Type 'Promise<Response<any, Record<string, any>, number> | undefined>' is not assignable to type 'Promise<void>'.
18.11             Type 'Response<any, Record<string, any>, number> | undefined' is not assignable to type 'void'.
18.11               Type 'Response<any, Record<string, any>, number>' is not assignable to type 'void'.
------
```


Please revert this change.